############################# English ############################
[en]
languageName = "En"
title = "Xpress Executive Services"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design And Managed By the [Desque](https://thedesque.com/)"

############################# Spanish ############################
[sp]
languageName = "Sp"
title = "Servicios Ejecutivos Xpress"
contentDir = "content/spanish" # content/spanish
weight = 2 
########### footer content ##########
footer_menu_left = "Empresa"
footer_menu_middle = "Producto"
footer_menu_right = "Apoyo"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Diseño y gestionado por el [Desque](https://thedesque.com/)"

